# generated by datamodel-codegen:
#   filename:  dashboard_data_schema_source.json
#   timestamp: 2022-12-29T06:28:33+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel, Extra, Field


class Task(BaseModel):
    class Config:
        extra = Extra.allow

    text: Optional[str] = None
    url: Optional[Any] = None


class Privilege(BaseModel):
    class Config:
        extra = Extra.allow

    text: Optional[str] = None
    url: Optional[Optional[str]] = None


class Level(BaseModel):
    class Config:
        extra = Extra.allow

    key: Optional[str] = None
    active: Optional[bool] = None
    name: Optional[str] = None
    tasks: Optional[List[Task]] = None
    privileges: Optional[List[Privilege]] = None


class SupportedLevels(BaseModel):
    class Config:
        extra = Extra.allow

    level1: Optional[str] = None
    level2: Optional[str] = None
    level2XBoxGold: Optional[str] = None


class Benefit(BaseModel):
    class Config:
        extra = Extra.allow

    key: Optional[str] = None
    text: Optional[str] = None
    url: Optional[Optional[str]] = None
    helpText: Optional[Optional[str]] = None
    supportedLevels: Optional[SupportedLevels] = None


class Attributes(BaseModel):
    class Config:
        extra = Extra.allow

    hidden: Optional[str] = None
    benefits: Optional[str] = None
    supportedLevelKeys: Optional[str] = None
    supportedLevelTitle: Optional[str] = None
    levelTitleMobile: Optional[str] = None
    activeLevel: Optional[str] = None
    give_eligible: Optional[str] = None
    destination: Optional[str] = None


class BenefitsPromotion(BaseModel):
    class Config:
        extra = Extra.allow

    benefits: Optional[List[Benefit]] = None
    supportedLevelKeys: Optional[List[str]] = None
    supportedLevelTitles: Optional[List[str]] = None
    supportedLevelTitlesMobile: Optional[List[str]] = None
    activeLevel: Optional[str] = None
    name: Optional[str] = None
    priority: Optional[int] = None
    attributes: Optional[Attributes] = None
    offerId: Optional[str] = None
    complete: Optional[bool] = None
    counter: Optional[int] = None
    activityProgress: Optional[int] = None
    activityProgressMax: Optional[int] = None
    pointProgressMax: Optional[int] = None
    pointProgress: Optional[int] = None
    promotionType: Optional[str] = None
    promotionSubtype: Optional[str] = None
    title: Optional[str] = None
    extBannerTitle: Optional[str] = None
    titleStyle: Optional[str] = None
    theme: Optional[str] = None
    description: Optional[str] = None
    extBannerDescription: Optional[str] = None
    descriptionStyle: Optional[str] = None
    showcaseTitle: Optional[str] = None
    showcaseDescription: Optional[str] = None
    imageUrl: Optional[str] = None
    dynamicImage: Optional[str] = None
    smallImageUrl: Optional[str] = None
    backgroundImageUrl: Optional[str] = None
    showcaseBackgroundImageUrl: Optional[str] = None
    showcaseBackgroundLargeImageUrl: Optional[str] = None
    promotionBackgroundLeft: Optional[str] = None
    promotionBackgroundRight: Optional[str] = None
    iconUrl: Optional[str] = None
    animatedIconUrl: Optional[str] = None
    animatedLargeBackgroundImageUrl: Optional[str] = None
    destinationUrl: Optional[str] = None
    linkText: Optional[str] = None
    hash: Optional[str] = None
    isRecurring: Optional[bool] = None
    isHidden: Optional[bool] = None
    isTestOnly: Optional[bool] = None
    isGiveEligible: Optional[bool] = None
    level: Optional[str] = None
    slidesCount: Optional[int] = None
    legalText: Optional[str] = None
    legalLinkText: Optional[str] = None


class LevelInfo(BaseModel):
    class Config:
        extra = Extra.allow

    activeLevel: Optional[str] = None
    activeLevelName: Optional[str] = None
    progress: Optional[int] = None
    progressMax: Optional[int] = None
    levels: Optional[List[Level]] = None
    benefitsPromotion: Optional[BenefitsPromotion] = None


class Description(BaseModel):
    class Config:
        extra = Extra.allow

    itemGroupText: Optional[str] = None
    smallText: Optional[str] = None
    largeText: Optional[str] = None
    legalText: Optional[str] = None
    showcaseTitle: Optional[str] = None
    showcaseDescription: Optional[str] = None


class RedeemGoal(BaseModel):
    class Config:
        extra = Extra.allow

    name: Optional[str] = None
    price: Optional[int] = None
    provider: Optional[str] = None
    category: Optional[str] = None
    title: Optional[str] = None
    smallImageUrl: Optional[str] = None
    mediumImageUrl: Optional[str] = None
    largeImageUrl: Optional[str] = None
    largeShowcaseImageUrl: Optional[str] = None
    description: Optional[Description] = None
    showcase: Optional[bool] = None
    showcaseInAllCategory: Optional[bool] = None
    originalPrice: Optional[int] = None
    discountedPrice: Optional[int] = None
    popular: Optional[bool] = None
    isTestOnly: Optional[bool] = None
    groupId: Optional[str] = None
    inGroup: Optional[bool] = None
    isDefaultItemInGroup: Optional[bool] = None
    groupTitle: Optional[str] = None
    groupImageUrl: Optional[str] = None
    groupShowcaseImageUrl: Optional[str] = None
    instantWinGameId: Optional[str] = None
    instantWinPlayAgainSku: Optional[str] = None
    isLowInStock: Optional[bool] = None
    isOutOfStock: Optional[bool] = None
    getCodeMessage: Optional[str] = None
    disableEmail: Optional[bool] = None
    stockMessage: Optional[str] = None
    comingSoonFlag: Optional[bool] = None
    isGenericDonation: Optional[bool] = None


class Attributes1(BaseModel):
    class Config:
        extra = Extra.allow

    foreground_color: Optional[str] = None
    image: Optional[str] = None
    small_image: Optional[str] = None
    bg_image: Optional[str] = None
    sc_bg_image: Optional[str] = None
    sc_bg_large_image: Optional[str] = None
    icon: Optional[str] = None
    xboxapp_icon: Optional[str] = None
    xboxapp_modal_header: Optional[str] = None
    xboxapp_modal_description: Optional[str] = None
    xboxapp_modal_primary_link_text: Optional[str] = None
    xboxapp_modal_primary_link_destination: Optional[str] = None
    app_package_family_name: Optional[str] = None
    xboxapp_modal_image: Optional[str] = None
    state: Optional[str] = None
    title: Optional[str] = None
    link_text: Optional[str] = None
    description: Optional[str] = None
    sc_title: Optional[str] = None
    sc_description: Optional[str] = None
    destination: Optional[str] = None
    answerScenario_Tag: Optional[str] = Field(None, alias='answerScenario.Tag')
    classification_Tag: Optional[str] = Field(None, alias='classification.Tag')
    classification_ShowProgress: Optional[str] = Field(
        None, alias='classification.ShowProgress'
    )
    type: Optional[str] = None
    recurring: Optional[str] = None
    progress: Optional[str] = None
    max: Optional[str] = None
    complete: Optional[str] = None
    offerid: Optional[str] = None
    give_eligible: Optional[str] = None
    xboxapp_destination: Optional[str] = None
    xboxapp_modal_secondary_link_text: Optional[str] = None
    xboxapp_modal_secondary_link_destination: Optional[str] = None
    animated_icon: Optional[str] = None


class PcSearchItem(BaseModel):
    class Config:
        extra = Extra.allow

    name: Optional[str] = None
    priority: Optional[int] = None
    attributes: Optional[Attributes1] = None
    offerId: Optional[str] = None
    complete: Optional[bool] = None
    counter: Optional[int] = None
    activityProgress: Optional[int] = None
    activityProgressMax: Optional[int] = None
    pointProgressMax: Optional[int] = None
    pointProgress: Optional[int] = None
    promotionType: Optional[str] = None
    promotionSubtype: Optional[str] = None
    title: Optional[str] = None
    extBannerTitle: Optional[str] = None
    titleStyle: Optional[str] = None
    theme: Optional[str] = None
    description: Optional[str] = None
    extBannerDescription: Optional[str] = None
    descriptionStyle: Optional[str] = None
    showcaseTitle: Optional[str] = None
    showcaseDescription: Optional[str] = None
    imageUrl: Optional[str] = None
    dynamicImage: Optional[str] = None
    smallImageUrl: Optional[str] = None
    backgroundImageUrl: Optional[str] = None
    showcaseBackgroundImageUrl: Optional[str] = None
    showcaseBackgroundLargeImageUrl: Optional[str] = None
    promotionBackgroundLeft: Optional[str] = None
    promotionBackgroundRight: Optional[str] = None
    iconUrl: Optional[str] = None
    animatedIconUrl: Optional[str] = None
    animatedLargeBackgroundImageUrl: Optional[str] = None
    destinationUrl: Optional[str] = None
    linkText: Optional[str] = None
    hash: Optional[str] = None
    isRecurring: Optional[bool] = None
    isHidden: Optional[bool] = None
    isTestOnly: Optional[bool] = None
    isGiveEligible: Optional[bool] = None
    level: Optional[str] = None
    slidesCount: Optional[int] = None
    legalText: Optional[str] = None
    legalLinkText: Optional[str] = None


class Attributes2(BaseModel):
    class Config:
        extra = Extra.allow

    foreground_color: Optional[str] = None
    image: Optional[str] = None
    small_image: Optional[str] = None
    bg_image: Optional[str] = None
    sc_bg_image: Optional[str] = None
    sc_bg_large_image: Optional[str] = None
    icon: Optional[str] = None
    xboxapp_icon: Optional[str] = None
    xboxapp_destination: Optional[str] = None
    xboxapp_modal_header: Optional[str] = None
    xboxapp_modal_primary_link_text: Optional[str] = None
    xboxapp_modal_primary_link_destination: Optional[str] = None
    xboxapp_modal_description: Optional[str] = None
    state: Optional[str] = None
    title: Optional[str] = None
    link_text: Optional[str] = None
    description: Optional[str] = None
    sc_title: Optional[str] = None
    sc_description: Optional[str] = None
    destination: Optional[str] = None
    answerScenario_Tag: Optional[str] = Field(None, alias='answerScenario.Tag')
    classification_Tag: Optional[str] = Field(None, alias='classification.Tag')
    classification_ShowProgress: Optional[str] = Field(
        None, alias='classification.ShowProgress'
    )
    type: Optional[str] = None
    recurring: Optional[str] = None
    progress: Optional[str] = None
    max: Optional[str] = None
    complete: Optional[str] = None
    offerid: Optional[str] = None
    give_eligible: Optional[str] = None


class MobileSearchItem(BaseModel):
    class Config:
        extra = Extra.allow

    name: Optional[str] = None
    priority: Optional[int] = None
    attributes: Optional[Attributes2] = None
    offerId: Optional[str] = None
    complete: Optional[bool] = None
    counter: Optional[int] = None
    activityProgress: Optional[int] = None
    activityProgressMax: Optional[int] = None
    pointProgressMax: Optional[int] = None
    pointProgress: Optional[int] = None
    promotionType: Optional[str] = None
    promotionSubtype: Optional[str] = None
    title: Optional[str] = None
    extBannerTitle: Optional[str] = None
    titleStyle: Optional[str] = None
    theme: Optional[str] = None
    description: Optional[str] = None
    extBannerDescription: Optional[str] = None
    descriptionStyle: Optional[str] = None
    showcaseTitle: Optional[str] = None
    showcaseDescription: Optional[str] = None
    imageUrl: Optional[str] = None
    dynamicImage: Optional[str] = None
    smallImageUrl: Optional[str] = None
    backgroundImageUrl: Optional[str] = None
    showcaseBackgroundImageUrl: Optional[str] = None
    showcaseBackgroundLargeImageUrl: Optional[str] = None
    promotionBackgroundLeft: Optional[str] = None
    promotionBackgroundRight: Optional[str] = None
    iconUrl: Optional[str] = None
    animatedIconUrl: Optional[str] = None
    animatedLargeBackgroundImageUrl: Optional[str] = None
    destinationUrl: Optional[str] = None
    linkText: Optional[str] = None
    hash: Optional[str] = None
    isRecurring: Optional[bool] = None
    isHidden: Optional[bool] = None
    isTestOnly: Optional[bool] = None
    isGiveEligible: Optional[bool] = None
    level: Optional[str] = None
    slidesCount: Optional[int] = None
    legalText: Optional[str] = None
    legalLinkText: Optional[str] = None


class Attributes3(BaseModel):
    class Config:
        extra = Extra.allow

    type: Optional[str] = None
    image: Optional[str] = None
    small_image: Optional[str] = None
    bg_image: Optional[str] = None
    sc_bg_image: Optional[str] = None
    sc_bg_large_image: Optional[str] = None
    icon: Optional[str] = None
    xboxapp_icon: Optional[str] = None
    xboxapp_header: Optional[str] = None
    xboxapp_description: Optional[str] = None
    xboxapp_modal_description: Optional[str] = None
    xboxapp_modal_header: Optional[str] = None
    xboxapp_modal_primary_link_text: Optional[str] = None
    xboxapp_modal_primary_link_destination: Optional[str] = None
    xboxapp_modal_secondary_link_text: Optional[str] = None
    xboxapp_modal_secondary_link_destination: Optional[str] = None
    state: Optional[str] = None
    title: Optional[str] = None
    link_text: Optional[str] = None
    description: Optional[str] = None
    sc_title: Optional[str] = None
    sc_description: Optional[str] = None
    destination: Optional[str] = None
    recurring: Optional[str] = None
    classification_ShowProgress: Optional[str] = Field(
        None, alias='classification.ShowProgress'
    )
    progress: Optional[str] = None
    max: Optional[str] = None
    complete: Optional[str] = None
    offerid: Optional[str] = None
    give_eligible: Optional[str] = None


class ShopAndEarnItem(BaseModel):
    class Config:
        extra = Extra.allow

    name: Optional[str] = None
    priority: Optional[int] = None
    attributes: Optional[Attributes3] = None
    offerId: Optional[str] = None
    complete: Optional[bool] = None
    counter: Optional[int] = None
    activityProgress: Optional[int] = None
    activityProgressMax: Optional[int] = None
    pointProgressMax: Optional[int] = None
    pointProgress: Optional[int] = None
    promotionType: Optional[str] = None
    promotionSubtype: Optional[str] = None
    title: Optional[str] = None
    extBannerTitle: Optional[str] = None
    titleStyle: Optional[str] = None
    theme: Optional[str] = None
    description: Optional[str] = None
    extBannerDescription: Optional[str] = None
    descriptionStyle: Optional[str] = None
    showcaseTitle: Optional[str] = None
    showcaseDescription: Optional[str] = None
    imageUrl: Optional[str] = None
    dynamicImage: Optional[str] = None
    smallImageUrl: Optional[str] = None
    backgroundImageUrl: Optional[str] = None
    showcaseBackgroundImageUrl: Optional[str] = None
    showcaseBackgroundLargeImageUrl: Optional[str] = None
    promotionBackgroundLeft: Optional[str] = None
    promotionBackgroundRight: Optional[str] = None
    iconUrl: Optional[str] = None
    animatedIconUrl: Optional[str] = None
    animatedLargeBackgroundImageUrl: Optional[str] = None
    destinationUrl: Optional[str] = None
    linkText: Optional[str] = None
    hash: Optional[str] = None
    isRecurring: Optional[bool] = None
    isHidden: Optional[bool] = None
    isTestOnly: Optional[bool] = None
    isGiveEligible: Optional[bool] = None
    level: Optional[str] = None
    slidesCount: Optional[int] = None
    legalText: Optional[str] = None
    legalLinkText: Optional[str] = None


class Attributes4(BaseModel):
    class Config:
        extra = Extra.allow

    type: Optional[str] = None
    title: Optional[str] = None
    link_text: Optional[str] = None
    description: Optional[str] = None
    foreground_color: Optional[str] = None
    image: Optional[str] = None
    recurring: Optional[str] = None
    destination: Optional[str] = None
    classification_ShowProgress: Optional[str] = Field(
        None, alias='classification.ShowProgress'
    )
    hidden: Optional[str] = None
    give_eligible: Optional[str] = None


class ActivityAndQuizItem(BaseModel):
    class Config:
        extra = Extra.allow

    name: Optional[str] = None
    priority: Optional[int] = None
    attributes: Optional[Attributes4] = None
    offerId: Optional[str] = None
    complete: Optional[bool] = None
    counter: Optional[int] = None
    activityProgress: Optional[int] = None
    activityProgressMax: Optional[int] = None
    pointProgressMax: Optional[int] = None
    pointProgress: Optional[int] = None
    promotionType: Optional[str] = None
    promotionSubtype: Optional[str] = None
    title: Optional[str] = None
    extBannerTitle: Optional[str] = None
    titleStyle: Optional[str] = None
    theme: Optional[str] = None
    description: Optional[str] = None
    extBannerDescription: Optional[str] = None
    descriptionStyle: Optional[str] = None
    showcaseTitle: Optional[str] = None
    showcaseDescription: Optional[str] = None
    imageUrl: Optional[str] = None
    dynamicImage: Optional[str] = None
    smallImageUrl: Optional[str] = None
    backgroundImageUrl: Optional[str] = None
    showcaseBackgroundImageUrl: Optional[str] = None
    showcaseBackgroundLargeImageUrl: Optional[str] = None
    promotionBackgroundLeft: Optional[str] = None
    promotionBackgroundRight: Optional[str] = None
    iconUrl: Optional[str] = None
    animatedIconUrl: Optional[str] = None
    animatedLargeBackgroundImageUrl: Optional[str] = None
    destinationUrl: Optional[str] = None
    linkText: Optional[str] = None
    hash: Optional[str] = None
    isRecurring: Optional[bool] = None
    isHidden: Optional[bool] = None
    isTestOnly: Optional[bool] = None
    isGiveEligible: Optional[bool] = None
    level: Optional[str] = None
    slidesCount: Optional[int] = None
    legalText: Optional[str] = None
    legalLinkText: Optional[str] = None


class DailyPointItem(BaseModel):
    class Config:
        extra = Extra.allow

    name: Optional[Any] = None
    priority: Optional[int] = None
    attributes: Optional[Any] = None
    offerId: Optional[str] = None
    complete: Optional[bool] = None
    counter: Optional[int] = None
    activityProgress: Optional[int] = None
    activityProgressMax: Optional[int] = None
    pointProgressMax: Optional[int] = None
    pointProgress: Optional[int] = None
    promotionType: Optional[str] = None
    promotionSubtype: Optional[str] = None
    title: Optional[str] = None
    extBannerTitle: Optional[str] = None
    titleStyle: Optional[str] = None
    theme: Optional[str] = None
    description: Optional[str] = None
    extBannerDescription: Optional[str] = None
    descriptionStyle: Optional[str] = None
    showcaseTitle: Optional[str] = None
    showcaseDescription: Optional[str] = None
    imageUrl: Optional[str] = None
    dynamicImage: Optional[str] = None
    smallImageUrl: Optional[str] = None
    backgroundImageUrl: Optional[str] = None
    showcaseBackgroundImageUrl: Optional[str] = None
    showcaseBackgroundLargeImageUrl: Optional[str] = None
    promotionBackgroundLeft: Optional[str] = None
    promotionBackgroundRight: Optional[str] = None
    iconUrl: Optional[str] = None
    animatedIconUrl: Optional[str] = None
    animatedLargeBackgroundImageUrl: Optional[str] = None
    destinationUrl: Optional[str] = None
    linkText: Optional[str] = None
    hash: Optional[str] = None
    isRecurring: Optional[bool] = None
    isHidden: Optional[bool] = None
    isTestOnly: Optional[bool] = None
    isGiveEligible: Optional[bool] = None
    level: Optional[str] = None
    slidesCount: Optional[int] = None
    legalText: Optional[str] = None
    legalLinkText: Optional[str] = None


class Counters(BaseModel):
    class Config:
        extra = Extra.allow

    pcSearch: Optional[List[PcSearchItem]] = None
    mobileSearch: Optional[List[MobileSearchItem]] = None
    shopAndEarn: Optional[List[ShopAndEarnItem]] = None
    activityAndQuiz: Optional[List[ActivityAndQuizItem]] = None
    dailyPoint: Optional[List[DailyPointItem]] = None


class Description1(BaseModel):
    class Config:
        extra = Extra.allow

    itemGroupText: Optional[str] = None
    smallText: Optional[str] = None
    largeText: Optional[str] = None
    legalText: Optional[str] = None
    showcaseTitle: Optional[str] = None
    showcaseDescription: Optional[str] = None


class CatalogItem(BaseModel):
    class Config:
        extra = Extra.allow

    name: Optional[str] = None
    price: Optional[int] = None
    provider: Optional[str] = None
    category: Optional[str] = None
    title: Optional[str] = None
    smallImageUrl: Optional[str] = None
    mediumImageUrl: Optional[str] = None
    largeImageUrl: Optional[str] = None
    largeShowcaseImageUrl: Optional[str] = None
    description: Optional[Description1] = None
    showcase: Optional[bool] = None
    showcaseInAllCategory: Optional[bool] = None
    originalPrice: Optional[int] = None
    discountedPrice: Optional[int] = None
    popular: Optional[bool] = None
    isTestOnly: Optional[bool] = None
    groupId: Optional[str] = None
    inGroup: Optional[bool] = None
    isDefaultItemInGroup: Optional[bool] = None
    groupTitle: Optional[str] = None
    groupImageUrl: Optional[str] = None
    groupShowcaseImageUrl: Optional[str] = None
    instantWinGameId: Optional[str] = None
    instantWinPlayAgainSku: Optional[str] = None
    isLowInStock: Optional[bool] = None
    isOutOfStock: Optional[bool] = None
    getCodeMessage: Optional[str] = None
    disableEmail: Optional[bool] = None
    stockMessage: Optional[str] = None
    comingSoonFlag: Optional[bool] = None
    isGenericDonation: Optional[bool] = None


class LastOrder(BaseModel):
    class Config:
        extra = Extra.allow

    id: Optional[str] = None
    price: Optional[int] = None
    status: Optional[str] = None
    sku: Optional[str] = None
    timestamp: Optional[str] = None
    catalogItem: Optional[CatalogItem] = None


class Attributes5(BaseModel):
    class Config:
        extra = Extra.allow

    hidden: Optional[str] = None
    activity_progress: Optional[str] = None
    offerid: Optional[str] = None
    give_eligible: Optional[str] = None
    destination: Optional[str] = None


class DashboardImpression(BaseModel):
    class Config:
        extra = Extra.allow

    name: Optional[str] = None
    priority: Optional[int] = None
    attributes: Optional[Attributes5] = None
    offerId: Optional[str] = None
    complete: Optional[bool] = None
    counter: Optional[int] = None
    activityProgress: Optional[int] = None
    activityProgressMax: Optional[int] = None
    pointProgressMax: Optional[int] = None
    pointProgress: Optional[int] = None
    promotionType: Optional[str] = None
    promotionSubtype: Optional[str] = None
    title: Optional[str] = None
    extBannerTitle: Optional[str] = None
    titleStyle: Optional[str] = None
    theme: Optional[str] = None
    description: Optional[str] = None
    extBannerDescription: Optional[str] = None
    descriptionStyle: Optional[str] = None
    showcaseTitle: Optional[str] = None
    showcaseDescription: Optional[str] = None
    imageUrl: Optional[str] = None
    dynamicImage: Optional[str] = None
    smallImageUrl: Optional[str] = None
    backgroundImageUrl: Optional[str] = None
    showcaseBackgroundImageUrl: Optional[str] = None
    showcaseBackgroundLargeImageUrl: Optional[str] = None
    promotionBackgroundLeft: Optional[str] = None
    promotionBackgroundRight: Optional[str] = None
    iconUrl: Optional[str] = None
    animatedIconUrl: Optional[str] = None
    animatedLargeBackgroundImageUrl: Optional[str] = None
    destinationUrl: Optional[str] = None
    linkText: Optional[str] = None
    hash: Optional[str] = None
    isRecurring: Optional[bool] = None
    isHidden: Optional[bool] = None
    isTestOnly: Optional[bool] = None
    isGiveEligible: Optional[bool] = None
    level: Optional[str] = None
    slidesCount: Optional[int] = None
    legalText: Optional[str] = None
    legalLinkText: Optional[str] = None


class ReferrerProgressInfo(BaseModel):
    class Config:
        extra = Extra.allow

    pointsEarned: Optional[int] = None
    pointsMax: Optional[int] = None
    isComplete: Optional[bool] = None
    promotions: Optional[List] = None


class UserStatus(BaseModel):
    class Config:
        extra = Extra.allow

    levelInfo: Optional[LevelInfo] = None
    availablePoints: Optional[int] = None
    lifetimePoints: Optional[int] = None
    lifetimePointsRedeemed: Optional[int] = None
    ePuid: Optional[str] = None
    redeemGoal: Optional[RedeemGoal] = None
    counters: Optional[Counters] = None
    lastOrder: Optional[LastOrder] = None
    dashboardImpression: Optional[DashboardImpression] = None
    referrerProgressInfo: Optional[ReferrerProgressInfo] = None
    isGiveModeOn: Optional[bool] = None
    giveBalance: Optional[int] = None
    lifetimeGivingPoints: Optional[int] = None
    isRewardsUser: Optional[bool] = None
    isMuidTrialUser: Optional[bool] = None


class Attributes6(BaseModel):
    class Config:
        extra = Extra.allow

    image: Optional[str] = None
    small_image: Optional[str] = None
    bg_image: Optional[str] = None
    sc_bg_image: Optional[str] = None
    sc_bg_large_image: Optional[str] = None
    icon: Optional[str] = None
    state: Optional[str] = None
    title: Optional[str] = None
    description: Optional[str] = None
    link_text: Optional[str] = None
    destination: Optional[str] = None
    type: Optional[str] = None
    animated_icon: Optional[str] = None
    promotional: Optional[str] = None
    max: Optional[str] = None
    progress: Optional[str] = None
    complete: Optional[str] = None
    offerid: Optional[str] = None
    give_eligible: Optional[str] = None


class PromotionalItem(BaseModel):
    class Config:
        extra = Extra.allow

    name: Optional[str] = None
    priority: Optional[int] = None
    attributes: Optional[Attributes6] = None
    offerId: Optional[str] = None
    complete: Optional[bool] = None
    counter: Optional[int] = None
    activityProgress: Optional[int] = None
    activityProgressMax: Optional[int] = None
    pointProgressMax: Optional[int] = None
    pointProgress: Optional[int] = None
    promotionType: Optional[str] = None
    promotionSubtype: Optional[str] = None
    title: Optional[str] = None
    extBannerTitle: Optional[str] = None
    titleStyle: Optional[str] = None
    theme: Optional[str] = None
    description: Optional[str] = None
    extBannerDescription: Optional[str] = None
    descriptionStyle: Optional[str] = None
    showcaseTitle: Optional[str] = None
    showcaseDescription: Optional[str] = None
    imageUrl: Optional[str] = None
    dynamicImage: Optional[str] = None
    smallImageUrl: Optional[str] = None
    backgroundImageUrl: Optional[str] = None
    showcaseBackgroundImageUrl: Optional[str] = None
    showcaseBackgroundLargeImageUrl: Optional[str] = None
    promotionBackgroundLeft: Optional[str] = None
    promotionBackgroundRight: Optional[str] = None
    iconUrl: Optional[str] = None
    animatedIconUrl: Optional[str] = None
    animatedLargeBackgroundImageUrl: Optional[str] = None
    destinationUrl: Optional[str] = None
    linkText: Optional[str] = None
    hash: Optional[str] = None
    isRecurring: Optional[bool] = None
    isHidden: Optional[bool] = None
    isTestOnly: Optional[bool] = None
    isGiveEligible: Optional[bool] = None
    level: Optional[str] = None
    slidesCount: Optional[int] = None
    legalText: Optional[str] = None
    legalLinkText: Optional[str] = None


class Attributes7(BaseModel):
    class Config:
        extra = Extra.allow

    image: Optional[str] = None
    small_image: Optional[str] = None
    bg_image: Optional[str] = None
    sc_bg_image: Optional[str] = None
    sc_bg_large_image: Optional[str] = None
    icon: Optional[str] = None
    state: Optional[str] = None
    title: Optional[str] = None
    description: Optional[str] = None
    link_text: Optional[str] = None
    destination: Optional[str] = None
    type: Optional[str] = None
    daily_set_date: Optional[str] = None
    animated_icon: Optional[str] = None
    max: Optional[str] = None
    progress: Optional[str] = None
    complete: Optional[str] = None
    offerid: Optional[str] = None
    give_eligible: Optional[str] = None


class Field12282022Item(BaseModel):
    class Config:
        extra = Extra.allow

    name: Optional[str] = None
    priority: Optional[int] = None
    attributes: Optional[Attributes7] = None
    offerId: Optional[str] = None
    complete: Optional[bool] = None
    counter: Optional[int] = None
    activityProgress: Optional[int] = None
    activityProgressMax: Optional[int] = None
    pointProgressMax: Optional[int] = None
    pointProgress: Optional[int] = None
    promotionType: Optional[str] = None
    promotionSubtype: Optional[str] = None
    title: Optional[str] = None
    extBannerTitle: Optional[str] = None
    titleStyle: Optional[str] = None
    theme: Optional[str] = None
    description: Optional[str] = None
    extBannerDescription: Optional[str] = None
    descriptionStyle: Optional[str] = None
    showcaseTitle: Optional[str] = None
    showcaseDescription: Optional[str] = None
    imageUrl: Optional[str] = None
    dynamicImage: Optional[str] = None
    smallImageUrl: Optional[str] = None
    backgroundImageUrl: Optional[str] = None
    showcaseBackgroundImageUrl: Optional[str] = None
    showcaseBackgroundLargeImageUrl: Optional[str] = None
    promotionBackgroundLeft: Optional[str] = None
    promotionBackgroundRight: Optional[str] = None
    iconUrl: Optional[str] = None
    animatedIconUrl: Optional[str] = None
    animatedLargeBackgroundImageUrl: Optional[str] = None
    destinationUrl: Optional[str] = None
    linkText: Optional[str] = None
    hash: Optional[str] = None
    isRecurring: Optional[bool] = None
    isHidden: Optional[bool] = None
    isTestOnly: Optional[bool] = None
    isGiveEligible: Optional[bool] = None
    level: Optional[str] = None
    slidesCount: Optional[int] = None
    legalText: Optional[str] = None
    legalLinkText: Optional[str] = None


class Attributes8(BaseModel):
    class Config:
        extra = Extra.allow

    image: Optional[str] = None
    small_image: Optional[str] = None
    bg_image: Optional[str] = None
    sc_bg_image: Optional[str] = None
    sc_bg_large_image: Optional[str] = None
    icon: Optional[str] = None
    state: Optional[str] = None
    title: Optional[str] = None
    description: Optional[str] = None
    link_text: Optional[str] = None
    destination: Optional[str] = None
    type: Optional[str] = None
    daily_set_date: Optional[str] = None
    animated_icon: Optional[str] = None
    max: Optional[str] = None
    progress: Optional[str] = None
    complete: Optional[str] = None
    offerid: Optional[str] = None
    give_eligible: Optional[str] = None


class Field12292022Item(BaseModel):
    class Config:
        extra = Extra.allow

    name: Optional[str] = None
    priority: Optional[int] = None
    attributes: Optional[Attributes8] = None
    offerId: Optional[str] = None
    complete: Optional[bool] = None
    counter: Optional[int] = None
    activityProgress: Optional[int] = None
    activityProgressMax: Optional[int] = None
    pointProgressMax: Optional[int] = None
    pointProgress: Optional[int] = None
    promotionType: Optional[str] = None
    promotionSubtype: Optional[str] = None
    title: Optional[str] = None
    extBannerTitle: Optional[str] = None
    titleStyle: Optional[str] = None
    theme: Optional[str] = None
    description: Optional[str] = None
    extBannerDescription: Optional[str] = None
    descriptionStyle: Optional[str] = None
    showcaseTitle: Optional[str] = None
    showcaseDescription: Optional[str] = None
    imageUrl: Optional[str] = None
    dynamicImage: Optional[str] = None
    smallImageUrl: Optional[str] = None
    backgroundImageUrl: Optional[str] = None
    showcaseBackgroundImageUrl: Optional[str] = None
    showcaseBackgroundLargeImageUrl: Optional[str] = None
    promotionBackgroundLeft: Optional[str] = None
    promotionBackgroundRight: Optional[str] = None
    iconUrl: Optional[str] = None
    animatedIconUrl: Optional[str] = None
    animatedLargeBackgroundImageUrl: Optional[str] = None
    destinationUrl: Optional[str] = None
    linkText: Optional[str] = None
    hash: Optional[str] = None
    isRecurring: Optional[bool] = None
    isHidden: Optional[bool] = None
    isTestOnly: Optional[bool] = None
    isGiveEligible: Optional[bool] = None
    level: Optional[str] = None
    slidesCount: Optional[int] = None
    legalText: Optional[str] = None
    legalLinkText: Optional[str] = None


class DailySetPromotions(BaseModel):
    class Config:
        extra = Extra.allow

    field_12_28_2022: Optional[List[Field12282022Item]] = Field(
        None, alias='12/28/2022'
    )
    field_12_29_2022: Optional[List[Field12292022Item]] = Field(
        None, alias='12/29/2022'
    )


class Attributes9(BaseModel):
    class Config:
        extra = Extra.allow

    hidden: Optional[str] = None
    type: Optional[str] = None
    title: Optional[str] = None
    image: Optional[str] = None
    activity_progress: Optional[str] = None
    last_updated: Optional[str] = None
    break_image: Optional[str] = None
    lifetime_max: Optional[str] = None
    bonus_points: Optional[str] = None
    give_eligible: Optional[str] = None
    destination: Optional[str] = None


class StreakPromotion(BaseModel):
    class Config:
        extra = Extra.allow

    lastUpdatedDate: Optional[str] = None
    breakImageUrl: Optional[str] = None
    lifetimeMaxValue: Optional[int] = None
    bonusPointsEarned: Optional[int] = None
    name: Optional[str] = None
    priority: Optional[int] = None
    attributes: Optional[Attributes9] = None
    offerId: Optional[str] = None
    complete: Optional[bool] = None
    counter: Optional[int] = None
    activityProgress: Optional[int] = None
    activityProgressMax: Optional[int] = None
    pointProgressMax: Optional[int] = None
    pointProgress: Optional[int] = None
    promotionType: Optional[str] = None
    promotionSubtype: Optional[str] = None
    title: Optional[str] = None
    extBannerTitle: Optional[str] = None
    titleStyle: Optional[str] = None
    theme: Optional[str] = None
    description: Optional[str] = None
    extBannerDescription: Optional[str] = None
    descriptionStyle: Optional[str] = None
    showcaseTitle: Optional[str] = None
    showcaseDescription: Optional[str] = None
    imageUrl: Optional[str] = None
    dynamicImage: Optional[str] = None
    smallImageUrl: Optional[str] = None
    backgroundImageUrl: Optional[str] = None
    showcaseBackgroundImageUrl: Optional[str] = None
    showcaseBackgroundLargeImageUrl: Optional[str] = None
    promotionBackgroundLeft: Optional[str] = None
    promotionBackgroundRight: Optional[str] = None
    iconUrl: Optional[str] = None
    animatedIconUrl: Optional[str] = None
    animatedLargeBackgroundImageUrl: Optional[str] = None
    destinationUrl: Optional[str] = None
    linkText: Optional[str] = None
    hash: Optional[str] = None
    isRecurring: Optional[bool] = None
    isHidden: Optional[bool] = None
    isTestOnly: Optional[bool] = None
    isGiveEligible: Optional[bool] = None
    level: Optional[str] = None
    slidesCount: Optional[int] = None
    legalText: Optional[str] = None
    legalLinkText: Optional[str] = None


class Attributes10(BaseModel):
    class Config:
        extra = Extra.allow

    hidden: Optional[str] = None
    type: Optional[str] = None
    title: Optional[str] = None
    description: Optional[str] = None
    image: Optional[str] = None
    animated_icon: Optional[str] = None
    activity_progress: Optional[str] = None
    activity_max: Optional[str] = None
    bonus_earned: Optional[str] = None
    break_description: Optional[str] = None
    give_eligible: Optional[str] = None
    destination: Optional[str] = None


class StreakBonusPromotion(BaseModel):
    class Config:
        extra = Extra.allow

    name: Optional[str] = None
    priority: Optional[int] = None
    attributes: Optional[Attributes10] = None
    offerId: Optional[str] = None
    complete: Optional[bool] = None
    counter: Optional[int] = None
    activityProgress: Optional[int] = None
    activityProgressMax: Optional[int] = None
    pointProgressMax: Optional[int] = None
    pointProgress: Optional[int] = None
    promotionType: Optional[str] = None
    promotionSubtype: Optional[str] = None
    title: Optional[str] = None
    extBannerTitle: Optional[str] = None
    titleStyle: Optional[str] = None
    theme: Optional[str] = None
    description: Optional[str] = None
    extBannerDescription: Optional[str] = None
    descriptionStyle: Optional[str] = None
    showcaseTitle: Optional[str] = None
    showcaseDescription: Optional[str] = None
    imageUrl: Optional[str] = None
    dynamicImage: Optional[str] = None
    smallImageUrl: Optional[str] = None
    backgroundImageUrl: Optional[str] = None
    showcaseBackgroundImageUrl: Optional[str] = None
    showcaseBackgroundLargeImageUrl: Optional[str] = None
    promotionBackgroundLeft: Optional[str] = None
    promotionBackgroundRight: Optional[str] = None
    iconUrl: Optional[str] = None
    animatedIconUrl: Optional[str] = None
    animatedLargeBackgroundImageUrl: Optional[str] = None
    destinationUrl: Optional[str] = None
    linkText: Optional[str] = None
    hash: Optional[str] = None
    isRecurring: Optional[bool] = None
    isHidden: Optional[bool] = None
    isTestOnly: Optional[bool] = None
    isGiveEligible: Optional[bool] = None
    level: Optional[str] = None
    slidesCount: Optional[int] = None
    legalText: Optional[str] = None
    legalLinkText: Optional[str] = None


class Attributes11(BaseModel):
    class Config:
        extra = Extra.allow

    image: Optional[str] = None
    small_image: Optional[str] = None
    bg_image: Optional[str] = None
    sc_bg_image: Optional[str] = None
    sc_bg_large_image: Optional[str] = None
    icon: Optional[str] = None
    state: Optional[str] = None
    title: Optional[str] = None
    description: Optional[str] = None
    link_text: Optional[str] = None
    destination: Optional[str] = None
    type: Optional[str] = None
    max: Optional[str] = None
    progress: Optional[str] = None
    complete: Optional[str] = None
    offerid: Optional[str] = None
    classification_PunchcardEndDate: Optional[str] = Field(
        None, alias='classification.PunchcardEndDate'
    )
    classification_Template: Optional[str] = Field(
        None, alias='classification.Template'
    )
    classification_TitleText: Optional[str] = Field(
        None, alias='classification.TitleText'
    )
    classification_DescriptionText: Optional[str] = Field(
        None, alias='classification.DescriptionText'
    )
    classification_PunchcardChildrenCount: Optional[str] = Field(
        None, alias='classification.PunchcardChildrenCount'
    )
    give_eligible: Optional[str] = None
    points_total: Optional[str] = None


class ParentPromotion(BaseModel):
    class Config:
        extra = Extra.allow

    name: Optional[str] = None
    priority: Optional[int] = None
    attributes: Optional[Attributes11] = None
    offerId: Optional[str] = None
    complete: Optional[bool] = None
    counter: Optional[int] = None
    activityProgress: Optional[int] = None
    activityProgressMax: Optional[int] = None
    pointProgressMax: Optional[int] = None
    pointProgress: Optional[int] = None
    promotionType: Optional[str] = None
    promotionSubtype: Optional[str] = None
    title: Optional[str] = None
    extBannerTitle: Optional[str] = None
    titleStyle: Optional[str] = None
    theme: Optional[str] = None
    description: Optional[str] = None
    extBannerDescription: Optional[str] = None
    descriptionStyle: Optional[str] = None
    showcaseTitle: Optional[str] = None
    showcaseDescription: Optional[str] = None
    imageUrl: Optional[str] = None
    dynamicImage: Optional[str] = None
    smallImageUrl: Optional[str] = None
    backgroundImageUrl: Optional[str] = None
    showcaseBackgroundImageUrl: Optional[str] = None
    showcaseBackgroundLargeImageUrl: Optional[str] = None
    promotionBackgroundLeft: Optional[str] = None
    promotionBackgroundRight: Optional[str] = None
    iconUrl: Optional[str] = None
    animatedIconUrl: Optional[str] = None
    animatedLargeBackgroundImageUrl: Optional[str] = None
    destinationUrl: Optional[str] = None
    linkText: Optional[str] = None
    hash: Optional[str] = None
    isRecurring: Optional[bool] = None
    isHidden: Optional[bool] = None
    isTestOnly: Optional[bool] = None
    isGiveEligible: Optional[bool] = None
    level: Optional[str] = None
    slidesCount: Optional[int] = None
    legalText: Optional[str] = None
    legalLinkText: Optional[str] = None


class Attributes12(BaseModel):
    class Config:
        extra = Extra.allow

    image: Optional[str] = None
    small_image: Optional[str] = None
    bg_image: Optional[str] = None
    sc_bg_image: Optional[str] = None
    sc_bg_large_image: Optional[str] = None
    icon: Optional[str] = None
    state: Optional[str] = None
    title: Optional[str] = None
    description: Optional[str] = None
    link_text: Optional[str] = None
    destination: Optional[str] = None
    type: Optional[str] = None
    max: Optional[str] = None
    progress: Optional[str] = None
    complete: Optional[str] = None
    offerid: Optional[str] = None
    parentPunchcards: Optional[str] = None
    give_eligible: Optional[str] = None
    classification_MatchCriteria: Optional[str] = Field(
        None, alias='classification.MatchCriteria'
    )
    classification_Products: Optional[str] = Field(
        None, alias='classification.Products'
    )


class ChildPromotion(BaseModel):
    class Config:
        extra = Extra.allow

    name: Optional[str] = None
    priority: Optional[int] = None
    attributes: Optional[Attributes12] = None
    offerId: Optional[str] = None
    complete: Optional[bool] = None
    counter: Optional[int] = None
    activityProgress: Optional[int] = None
    activityProgressMax: Optional[int] = None
    pointProgressMax: Optional[int] = None
    pointProgress: Optional[int] = None
    promotionType: Optional[str] = None
    promotionSubtype: Optional[str] = None
    title: Optional[str] = None
    extBannerTitle: Optional[str] = None
    titleStyle: Optional[str] = None
    theme: Optional[str] = None
    description: Optional[str] = None
    extBannerDescription: Optional[str] = None
    descriptionStyle: Optional[str] = None
    showcaseTitle: Optional[str] = None
    showcaseDescription: Optional[str] = None
    imageUrl: Optional[str] = None
    dynamicImage: Optional[str] = None
    smallImageUrl: Optional[str] = None
    backgroundImageUrl: Optional[str] = None
    showcaseBackgroundImageUrl: Optional[str] = None
    showcaseBackgroundLargeImageUrl: Optional[str] = None
    promotionBackgroundLeft: Optional[str] = None
    promotionBackgroundRight: Optional[str] = None
    iconUrl: Optional[str] = None
    animatedIconUrl: Optional[str] = None
    animatedLargeBackgroundImageUrl: Optional[str] = None
    destinationUrl: Optional[str] = None
    linkText: Optional[str] = None
    hash: Optional[str] = None
    isRecurring: Optional[bool] = None
    isHidden: Optional[bool] = None
    isTestOnly: Optional[bool] = None
    isGiveEligible: Optional[bool] = None
    level: Optional[str] = None
    slidesCount: Optional[int] = None
    legalText: Optional[str] = None
    legalLinkText: Optional[str] = None


class PunchCard(BaseModel):
    class Config:
        extra = Extra.allow

    name: Optional[str] = None
    parentPromotion: Optional[ParentPromotion] = None
    childPromotions: Optional[List[ChildPromotion]] = None


class DashboardFlights(BaseModel):
    class Config:
        extra = Extra.allow

    dashboardbannernav: Optional[str] = None
    give_eligible: Optional[str] = None
    destination: Optional[str] = None


class Attributes13(BaseModel):
    class Config:
        extra = Extra.allow

    image: Optional[str] = None
    small_image: Optional[str] = None
    bg_image: Optional[str] = None
    sc_bg_image: Optional[str] = None
    sc_bg_large_image: Optional[str] = None
    icon: Optional[str] = None
    state: Optional[str] = None
    title: Optional[str] = None
    description: Optional[str] = None
    link_text: Optional[str] = None
    destination: Optional[str] = None
    type: Optional[str] = None
    animated_icon: Optional[str] = None
    max: Optional[str] = None
    progress: Optional[str] = None
    complete: Optional[str] = None
    offerid: Optional[str] = None
    give_eligible: Optional[str] = None
    promotional: Optional[str] = None
    sc_title: Optional[str] = None
    sc_description: Optional[str] = None
    daily_set_date: Optional[str] = None


class MorePromotion(BaseModel):
    class Config:
        extra = Extra.allow

    name: Optional[str] = None
    priority: Optional[int] = None
    attributes: Optional[Attributes13] = None
    offerId: Optional[str] = None
    complete: Optional[bool] = None
    counter: Optional[int] = None
    activityProgress: Optional[int] = None
    activityProgressMax: Optional[int] = None
    pointProgressMax: Optional[int] = None
    pointProgress: Optional[int] = None
    promotionType: Optional[str] = None
    promotionSubtype: Optional[str] = None
    title: Optional[str] = None
    extBannerTitle: Optional[str] = None
    titleStyle: Optional[str] = None
    theme: Optional[str] = None
    description: Optional[str] = None
    extBannerDescription: Optional[str] = None
    descriptionStyle: Optional[str] = None
    showcaseTitle: Optional[str] = None
    showcaseDescription: Optional[str] = None
    imageUrl: Optional[str] = None
    dynamicImage: Optional[str] = None
    smallImageUrl: Optional[str] = None
    backgroundImageUrl: Optional[str] = None
    showcaseBackgroundImageUrl: Optional[str] = None
    showcaseBackgroundLargeImageUrl: Optional[str] = None
    promotionBackgroundLeft: Optional[str] = None
    promotionBackgroundRight: Optional[str] = None
    iconUrl: Optional[str] = None
    animatedIconUrl: Optional[str] = None
    animatedLargeBackgroundImageUrl: Optional[str] = None
    destinationUrl: Optional[str] = None
    linkText: Optional[str] = None
    hash: Optional[str] = None
    isRecurring: Optional[bool] = None
    isHidden: Optional[bool] = None
    isTestOnly: Optional[bool] = None
    isGiveEligible: Optional[bool] = None
    level: Optional[str] = None
    slidesCount: Optional[int] = None
    legalText: Optional[str] = None
    legalLinkText: Optional[str] = None


class Description2(BaseModel):
    class Config:
        extra = Extra.allow

    itemGroupText: Optional[str] = None
    smallText: Optional[str] = None
    largeText: Optional[str] = None
    legalText: Optional[str] = None
    showcaseTitle: Optional[str] = None
    showcaseDescription: Optional[str] = None


class SuggestedReward(BaseModel):
    class Config:
        extra = Extra.allow

    name: Optional[str] = None
    price: Optional[int] = None
    provider: Optional[str] = None
    category: Optional[str] = None
    title: Optional[str] = None
    smallImageUrl: Optional[str] = None
    mediumImageUrl: Optional[str] = None
    largeImageUrl: Optional[str] = None
    largeShowcaseImageUrl: Optional[str] = None
    description: Optional[Description2] = None
    showcase: Optional[bool] = None
    showcaseInAllCategory: Optional[bool] = None
    originalPrice: Optional[int] = None
    discountedPrice: Optional[int] = None
    popular: Optional[bool] = None
    isTestOnly: Optional[bool] = None
    groupId: Optional[str] = None
    inGroup: Optional[bool] = None
    isDefaultItemInGroup: Optional[bool] = None
    groupTitle: Optional[str] = None
    groupImageUrl: Optional[str] = None
    groupShowcaseImageUrl: Optional[str] = None
    instantWinGameId: Optional[str] = None
    instantWinPlayAgainSku: Optional[str] = None
    isLowInStock: Optional[bool] = None
    isOutOfStock: Optional[bool] = None
    getCodeMessage: Optional[str] = None
    disableEmail: Optional[bool] = None
    stockMessage: Optional[str] = None
    comingSoonFlag: Optional[bool] = None
    isGenericDonation: Optional[bool] = None


class Attributes14(BaseModel):
    class Config:
        extra = Extra.allow

    type: Optional[str] = None
    subtype: Optional[str] = None
    hidden: Optional[str] = None
    slides: Optional[str] = None
    slide_0_title: Optional[str] = None
    slide_0_description: Optional[str] = None
    slide_0_linkText: Optional[str] = None
    slide_0_taggedItem: Optional[str] = None
    slide_1_title: Optional[str] = None
    slide_1_description: Optional[str] = None
    slide_1_linkText: Optional[str] = None
    slide_1_taggedItem: Optional[str] = None
    slide_2_title: Optional[str] = None
    slide_2_description: Optional[str] = None
    slide_2_linkText: Optional[str] = None
    slide_2_taggedItem: Optional[str] = None
    activity_progress: Optional[str] = None
    offerid: Optional[str] = None
    progress: Optional[str] = None
    max: Optional[str] = None
    complete: Optional[str] = None
    give_eligible: Optional[str] = None
    destination: Optional[str] = None


class Promotion(BaseModel):
    class Config:
        extra = Extra.allow

    name: Optional[str] = None
    priority: Optional[int] = None
    attributes: Optional[Attributes14] = None
    offerId: Optional[str] = None
    complete: Optional[bool] = None
    counter: Optional[int] = None
    activityProgress: Optional[int] = None
    activityProgressMax: Optional[int] = None
    pointProgressMax: Optional[int] = None
    pointProgress: Optional[int] = None
    promotionType: Optional[str] = None
    promotionSubtype: Optional[str] = None
    title: Optional[str] = None
    extBannerTitle: Optional[str] = None
    titleStyle: Optional[str] = None
    theme: Optional[str] = None
    description: Optional[str] = None
    extBannerDescription: Optional[str] = None
    descriptionStyle: Optional[str] = None
    showcaseTitle: Optional[str] = None
    showcaseDescription: Optional[str] = None
    imageUrl: Optional[str] = None
    dynamicImage: Optional[str] = None
    smallImageUrl: Optional[str] = None
    backgroundImageUrl: Optional[str] = None
    showcaseBackgroundImageUrl: Optional[str] = None
    showcaseBackgroundLargeImageUrl: Optional[str] = None
    promotionBackgroundLeft: Optional[str] = None
    promotionBackgroundRight: Optional[str] = None
    iconUrl: Optional[str] = None
    animatedIconUrl: Optional[str] = None
    animatedLargeBackgroundImageUrl: Optional[str] = None
    destinationUrl: Optional[str] = None
    linkText: Optional[str] = None
    hash: Optional[str] = None
    isRecurring: Optional[bool] = None
    isHidden: Optional[bool] = None
    isTestOnly: Optional[bool] = None
    isGiveEligible: Optional[bool] = None
    level: Optional[str] = None
    slidesCount: Optional[int] = None
    legalText: Optional[str] = None
    legalLinkText: Optional[str] = None


class NextLink(BaseModel):
    class Config:
        extra = Extra.allow

    text: Optional[str] = None
    url: Optional[str] = None


class CloseLink(BaseModel):
    class Config:
        extra = Extra.allow

    text: Optional[Any] = None
    url: Optional[str] = None


class Slide(BaseModel):
    class Config:
        extra = Extra.allow

    slideShowTourId: Optional[str] = None
    id: Optional[int] = None
    title: Optional[str] = None
    image2Title: Optional[Any] = None
    image3Title: Optional[Any] = None
    image4Title: Optional[Any] = None
    description: Optional[str] = None
    image2Description: Optional[Any] = None
    image3Description: Optional[Any] = None
    image4Description: Optional[Any] = None
    imageUrl: Optional[Any] = None
    image2Url: Optional[Any] = None
    image3Url: Optional[Any] = None
    image4Url: Optional[Any] = None
    layout: Optional[Any] = None
    actionButtonText: Optional[Any] = None
    actionButtonUrl: Optional[Any] = None
    foregroundImageUrl: Optional[Any] = None
    taggedItem: Optional[str] = None
    backLink: Optional[Any] = None
    nextLink: Optional[NextLink] = None
    closeLink: Optional[CloseLink] = None


class Streaks(BaseModel):
    class Config:
        extra = Extra.allow

    promotion: Optional[Promotion] = None
    slides: Optional[List[Slide]] = None


class CoachMarks(BaseModel):
    class Config:
        extra = Extra.allow

    streaks: Optional[Streaks] = None


class WelcomeTour(BaseModel):
    class Config:
        extra = Extra.allow

    promotion: Optional[Any] = None
    slides: Optional[List] = None


class GeneratedDashboardDataModel(BaseModel):
    class Config:
        extra = Extra.allow

    userStatus: Optional[UserStatus] = None
    promotionalItem: Optional[PromotionalItem] = None
    dailySetPromotions: Optional[DailySetPromotions] = None
    streakPromotion: Optional[StreakPromotion] = None
    streakBonusPromotions: Optional[List[StreakBonusPromotion]] = None
    punchCards: Optional[List[PunchCard]] = None
    dashboardFlights: Optional[DashboardFlights] = None
    morePromotions: Optional[List[MorePromotion]] = None
    suggestedRewards: Optional[List[SuggestedReward]] = None
    coachMarks: Optional[CoachMarks] = None
    welcomeTour: Optional[WelcomeTour] = None
